# Dataset(CCVID)
dataset:
  root: dataset
  train_txt: dataset/train.txt
  num_frames: 8
  sampling: uniform
  image_size: 256
  crop_size: 224

# Model
model:
  # Branch A: Clothed Body Stream
  # T frames => Vit-B => T X 768 => TT => T X 768 (time aware) => LP => T X 512
  vit_out_dim: 768
  temporal_heads: 8
  temporal_layers: 2
  temporal_dropout: 0.1
  branch_a_out_dim: 512

  # Branch B: Bare Body Stream
  # T frames => ResNet-50 => T X 2048 => GRU => 512 => regressor =>
  # SMPL parameters (82) => token encoder => N X 512
  resnet_out_dim: 2048
  hmr2_out_dim: 226
  gru_layers: 2
  smpl_num_tokens: 8 # number of tokens (N) to represent the SMPL parameters
  branch_b_out_dim: 512

  # Fusion: Cross Attention
  # Q: T X 512 (Branch A) attends to K,V: N X 512 (Branch B)
  # Output: T X 512 => avg pool => 512 => Linear + LayerNorm => 512
  fusion_heads: 8 # cross attention heads
  fused_dim: 512

  # Heads
  num_classes: 75 # approximate number of training identities

# Smoke test
smoke:
  num_sequences: 8
  batch_size: 2
  device: cuda

# Training
train:
  device: cuda
  num_epochs: 6
  batch_size: 2
  num_workers: 0
  base_lr: 0.0001
  backbone_lr: 0.00001
  weight_decay: 0.01
  lr_step: 10
  lr_gamma: 0.1
  unfreeze_hmr_epoch: 3
  unfreeze_all_epoch: 5
  save_every: 2
  smoke_subset: 256

# Evaluate
evaluate:
  device: cuda
  batch_size: 2
  num_workers: 0
  gallery_subset: 4
  query_subset: 2
